// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5nM0VUqj8kUUwV-2jaADnLxT-kxcxsyo',
    appId: '1:357710887433:web:d3423ff62a5e3df43396d8',
    messagingSenderId: '357710887433',
    projectId: 'kitchenflow-76b6d',
    authDomain: 'kitchenflow-76b6d.firebaseapp.com',
    storageBucket: 'kitchenflow-76b6d.firebasestorage.app',
    measurementId: 'G-K5G4WR1GV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUsQd8drLJzqbwPMCKNJUgEVdBZUJrZU',
    appId: '1:357710887433:android:ff1dcc84611463cf3396d8',
    messagingSenderId: '357710887433',
    projectId: 'kitchenflow-76b6d',
    storageBucket: 'kitchenflow-76b6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYWt1aeR6K_t2-U7wlSnqTGkKfY_Jazaw',
    appId: '1:357710887433:ios:a23d1a1b4a3123213396d8',
    messagingSenderId: '357710887433',
    projectId: 'kitchenflow-76b6d',
    storageBucket: 'kitchenflow-76b6d.firebasestorage.app',
    iosBundleId: 'com.example.flutterCleanArchitectureTemplate',
  );
}
